name: Code Coverage

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage codecov

      # Step 4: Run tests and collect coverage
      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report
          coverage xml

      # Step 5: Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
